spring:
  application:
    name: eureka

server:
  port: 8762

eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8763/eureka/